resources:
  containers:
  - container: postgres_13
    image: postgres:13
  - container: nginx
    image: nginx


pool:
  name: default

container: postgres_13
services:
  nginxPP: nginx

steps:
- script: |
    curl nginxPP
  displayName: Show that nginx is running