resources:
  containers:
  - container: postgres_13
    image: postgres:13
  - container: nginx
    image: nginx
    ports:
    - 8080:8080


pool:
  name: default

container: postgres_13
services:
  nginx: nginx

steps:
- script: |
    curl nginx
  displayName: Show that nginx is running