resources:
  containers:
  - container: my_container
    image: buildpack-deps:focal
  - container: nginx
    image: nginx


pool:
  name: default

container: my_container
services:
  nginxPP: nginx

steps:
- script: |
    curl nginxPP
  displayName: Show that nginx is running